"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Lessons = exports.Roles = exports.DataBase = void 0;
const tslib_1 = require("tslib");
var DataBase_1 = require("./DataBase");
Object.defineProperty(exports, "DataBase", { enumerable: true, get: function () { return DataBase_1.DataBase; } });
var utils_1 = require("./Models/utils");
Object.defineProperty(exports, "Roles", { enumerable: true, get: function () { return utils_1.Roles; } });
Object.defineProperty(exports, "Lessons", { enumerable: true, get: function () { return utils_1.Lessons; } });
tslib_1.__exportStar(require("./DataBase"), exports);
