name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i -g typescript    
      - run: npm ci --ignore-scripts
      - run: npm run build --if-present
        env:
          CI: true
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci --ignore-scripts
      - run: tsc
      - run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
